### ISSUE TITLE
Getting random failures in neovim

### ISSUE THREAD

**Issue by deltaskelta** [Galooshi/vim-import-js#25] opened 2017-07-21 02:46 UTC
I tried to add the line `:call ch_logfile('channel_log.txt', 'w')` in neovim as line 1 of my `init.vim` file and it gave me an error that said...

```
line    1:
E117: Unknown function: ch_logfile
```

As for the error that ImportJS is giving me, Ive just closed out of vim and it went away, but it has been popping up regularly so I will post it here when it happens next

**Comment by deltaskelta** [comment] 2017-07-21 02:59
I just got the error again

```
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    1:
E474: Trailing characters: {"messages":[],"fileContent":"import { ControlLabel, FormControl } from 'react-bootstrap';\nimport { connect } from 'react-re
dux';\nimport React, { PropTypes } from 'react';\n\nimport { updateWalletAddress } from '../actions/defs';\n\nconst ExchangeWalletSettingsForm = ({ exNa
me, settings, onSettingChange }) => {\n  console.log(settings.BTC);\n  console.log(settings.BTC === undefined);\n  return (\n    <div>\n      <ControlLa
bel>Wallet Addresses:</ControlLabel>\n      <FormControl\n        name=\"BTC\"\n        onChange={e => onSettingChange(exName, 'address', e)}\n        t
ype=\"text\"\n        placeholder=\"btc\"\n        values={settings.BTC === undefined ? '' : settings.BTC.address}\n      />\n      <FormControl\n
  name=\"eth\"\n        onChange={e => onSettingChange(exName, e)}\n        type=\"text\"\n        placeholder=\"eth\"\n        values={settings.ETH ===
 undefined ? '' : settings.ETH.address}\n      />\n      <FormControl\n        name=\"etc\"\n        onChange={e
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    1:
E474: Failed to parse {"messages":[],"fileContent":"import { ControlLabel, FormControl } from 'react-bootstrap';\nimport { connect } from 'react-redux';
\nimport React, { PropTypes } from 'react';\n\nimport { updateWalletAddress } from '../actions/defs';\n\nconst ExchangeWalletSettingsForm = ({ exName, s
ettings, onSettingChange }) => {\n  console.log(settings.BTC);\n  console.log(settings.BTC === undefined);\n  return (\n    <div>\n      <ControlLabel>W
allet Addresses:</ControlLabel>\n      <FormControl\n        name=\"BTC\"\n        onChange={e => onSettingChange(exName, 'address', e)}\n        type=\
"text\"\n        placeholder=\"btc\"\n        values={settings.BTC === undefined ? '' : settings.BTC.address}\n      />\n      <FormControl\n        nam
e=\"eth\"\n        onChange={e => onSettingChange(exName, e)}\n        type=\"text\"\n        placeholder=\"eth\"\n        values={settings.ETH === unde
fined ? '' : settings.ETH.address}\n      />\n      <FormControl\n        name=\"etc\"\n        onChange={e => o
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    3:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    8:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line   13:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line   24:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line   27:
E715: Dictionary required
"exchange-wallet-settings.js" 90L, 2575C written
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    1:
E474: Trailing characters: {"messages":["SyntaxError: Identifier directly after number (1:1)"],"fileContent":"0import { ControlLabel, FormControl } from
 'react-bootstrap';\nimport { connect } from 'react-redux';\nimport React, { PropTypes } from 'react';\n\nimport { updateWalletAddress } from '../action
s/defs';\n\nconst ExchangeWalletSettingsForm = ({ exName, settings, onSettingChange }) => {\n  return (\n    <div>\n      <ControlLabel>Wallet Addresses
:</ControlLabel>\n      <FormControl\n        name=\"BTC\"\n        onChange={e => onSettingChange(exName, 'address', e)}\n        type=\"text\"\n
  placeholder=\"btc\"\n        values={settings.BTC === undefined ? '' : settings.BTC.address}\n      />\n      <FormControl\n        name=\"eth\"\n
    onChange={e => onSettingChange(exName, e)}\n        type=\"text\"\n        placeholder=\"eth\"\n        values={settings.ETH === undefined ? '' : se
ttings.ETH.address}\n      />\n      <FormControl\n        name=\"etc\"\n        onChange={e => onSettingChange(
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    1:
E474: Failed to parse {"messages":["SyntaxError: Identifier directly after number (1:1)"],"fileContent":"0import { ControlLabel, FormControl } from 'rea
ct-bootstrap';\nimport { connect } from 'react-redux';\nimport React, { PropTypes } from 'react';\n\nimport { updateWalletAddress } from '../actions/def
s';\n\nconst ExchangeWalletSettingsForm = ({ exName, settings, onSettingChange }) => {\n  return (\n    <div>\n      <ControlLabel>Wallet Addresses:</Co
ntrolLabel>\n      <FormControl\n        name=\"BTC\"\n        onChange={e => onSettingChange(exName, 'address', e)}\n        type=\"text\"\n        pla
ceholder=\"btc\"\n        values={settings.BTC === undefined ? '' : settings.BTC.address}\n      />\n      <FormControl\n        name=\"eth\"\n        o
nChange={e => onSettingChange(exName, e)}\n        type=\"text\"\n        placeholder=\"eth\"\n        values={settings.ETH === undefined ? '' : setting
s.ETH.address}\n      />\n      <FormControl\n        name=\"etc\"\n        onChange={e => onSettingChange(exNam
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    3:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line    8:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line   13:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line   24:
E715: Dictionary required
Error detected while processing function <SNR>53_JobHandler[4]..importjs#ParseResult:
line   27:
E715: Dictionary required
```

**Comment by trotzig** [comment] 2017-07-31 15:09
Ah, it looks like `ch_logfile` only works in regular vim, not neovim. 

It looks like this error is thrown whenever there's a syntax error in the javascript file you are currently editing. we're not handling this correctly in neo vim it seems. I'm not a neovim user myself, so any help I can get here will be appreciated!

**Comment by deltaskelta** [comment] 2017-08-07 11:51
I still randomly get the error and I am trying to do all I can to narrow it down when it happens but I haven't been able to reliably reproduce it yet.

**Comment by trotzig** [comment] 2017-08-07 12:11
Can you try forcing a js syntax error? This is where I saw the error when I reproduced in neovim last time. Try running fix imports on something like this:

```js
function boo() {
```

(notice the missing closing curly).

**Comment by deltaskelta** [comment] 2017-08-08 02:49
When I do that I just get `SyntaxError: unexpected token` and not the big failure I mentioned above

**Comment by trotzig** [comment] 2017-08-08 12:30
Oh, odd. I wonder if it's worth editing the source locally on your machine and add some more logging inside ParseResult. Somewhere around here:
https://github.com/Galooshi/vim-import-js/blob/862ca76e685e8563385b0dcd8f7d83e47ba2ce09/autoload/importjs.vim#L80

**Comment by deltaskelta** [comment] 2017-08-08 13:07
ok ill try to get a log when it happens next time

**Comment by trotzig** [comment] 2017-08-08 13:13
:) thanks for helping out!

**Comment by deltaskelta** [comment] 2017-08-10 09:29
It hasn't happened again so I don't have any logs to prove it, but I am pretty sure this is happening because it is interfering with an asynchronous linter that I have (`w0rp/ale`) and I need to work importjs in with the async workflow instead of having it run independently...

with `ale` in particular, in order to work it into their pattern I would need to call a function that will return the changed lines to me. I am not very good with understanding the vimscript in your library, but is there any way for me to call `:ImportJSFix` like that so it would return the changed lines to me?

If so I can add some docs about how to incorporate it into ale once I get it figured out.

**Comment by trotzig** [comment] 2017-08-10 11:58
Ah, I see. Right off the bat, there's no way of getting only the changed lines from `:ImportJSFix`. This is something that we've talked about supporting for import-js however, to reduce the size of the data to send back from the commands. But it hasn't been implemented yet. I don't think it would be hard, and it could probably be added to import-js as an opt-in. If the client sends a certain flag, we can run the resulting file content through something like https://www.npmjs.com/package/text-diff and return the diff from the original content.

**Comment by deltaskelta** [comment] 2017-08-10 13:19
OK. Thanks for all the quick responses. I've tried a few simple workarounds with no luck. I think for now I will just stick to calling it manually and be careful not to make it clash with anything. 

JS CLI tools are a little out of my area, so I won't be able to help there much at this moment :(

**Comment by trotzig** [comment] 2017-08-10 13:39
Got it! Thanks for taking the time to report your issue. This will benefit others running into the same issue. 

I'm going to close this as I don't see any immediate action items. Let me know if you disagree!

**Closed by trotzig** 2017-08-10 13:39 UTC
